identity:
  name: bar_chart
  author: Dify
  label:
    en_US: Bar Chart
    zh_Hans: 柱状图
  icon: icon.svg
description:
  human:
    en_US: Bar chart
    zh_Hans: 柱状图
  llm: generate a bar chart with input data
parameters:
  - name: data
    type: string
    required: true
    label:
      en_US: data
      zh_Hans: 数据
    human_description:
      en_US: data for generating bar chart
      zh_Hans: 用于生成柱状图的数据
    llm_description: data for generating bar chart, data should be a string contains a list of numbers like "1;2;3;4;5"
    form: llm
  - name: x_axis
    type: string
    required: false
    label:
      en_US: X Axis
      zh_Hans: x 轴
    human_description:
      en_US: X axis for bar chart
      zh_Hans: 柱状图的 x 轴
    llm_description: x axis for bar chart, x axis should be a string contains a list of texts like "a;b;c;1;2" in order to match the data
    form: llm
